### ISSUE TITLE
(Key Overlay) Animation of pressing a key missing inputs (?) and not working as intended

### ISSUE THREAD

**Issue by Flapczek** [HosizoraN/SonataOverlay#1]
https://github.com/HosizoraN/SonataOverlay/assets/52840700/3dc8167f-4dd5-47c4-ac59-7e8dc0a6ad4e

Idk if it's the problem of tosu itself or the overlay, but im guessing it's the tosu issue

**Comment by HosizoraN** [comment]
> 2024-06-20.16-31-48.mp4 
> Idk if it's the problem of tosu itself or the overlay, but im guessing it's the tosu issue

can i check tosu settings?

**Comment by Flapczek** [comment]
> > 2024-06-20.16-31-48.mp4
> > Idk if it's the problem of tosu itself or the overlay, but im guessing it's the tosu issue
> 
> can i check tosu settings?

![image](https://github.com/HosizoraN/SonataOverlay/assets/52840700/150fd3b1-b110-41f2-8ca6-efebbbc6f82e)

**Comment by HosizoraN** [comment]
> > > 2024-06-20.16-31-48.mp4
> > > Idk if it's the problem of tosu itself or the overlay, but im guessing it's the tosu issue
> > 
> > 
> > can i check tosu settings?
> 
> ![image](https://private-user-images.githubusercontent.com/52840700/341459524-150fd3b1-b110-41f2-8ca6-efebbbc6f82e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTU0MjAsIm5iZiI6MTcxODg5NTEyMCwicGF0aCI6Ii81Mjg0MDcwMC8zNDE0NTk1MjQtMTUwZmQzYjEtYjExMC00MWYyLThjYTYtZWZlYmJiYzZmODJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE0NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNTZkYjllNjUyODU4NjJmOTNhZDk4MTRhYjZjMDI5MWUyOWYzNzZmNjRmN2M2Yjk1NWVjNjZmZmY5NzM0NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQBdygH77tbqYaS9ShwQ4ZgNYm7N7Rce9V46Vj9ansI)

set the PRECISE_DATA_POLL_RATE to 0 or 10 (if hardware issue)

**Comment by Flapczek** [comment]
oh that would make sense....

30 is the most optimal value for my hardware, now its working fine
